name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      # - run: cd project/project-management-api && git fetch origin -p && git merge origin/master && yarn install && yarn docker:deploy
      # - run: git fetch origin -p && git merge origin/master && yarn install && yarn docker:deploy
      - run: cd /root/project/e-commerce-api && git fetch origin -p && git merge origin/main && npx yarn install && npx yarn docker:deploy

  # deploy:
  # runs-on: ubuntu-latest
  # runs-on: self-hosted
  # steps:
  #   - uses: actions/checkout@v1
  #   - name: Push to server
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: 171.237.246.55
  #       username: ubuntu
  #       password: houzerd1
  #       script: cd code/task-manage-api && git fetch origin && git merge origin/master && yarn install && yarn docker:deploy
