name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      # - run: cd project/project-management-api && git fetch origin -p && git merge origin/master && yarn install && yarn docker:deploy
      # - run: git fetch origin -p && git merge origin/master && yarn install && yarn docker:deploy
      - run: cd /root/project/e-commerce-api && git fetch origin -p && git merge origin/main && npx yarn install && npx yarn docker:deploy
